require(... .. ".bar")
require(... .. ".notifications")
require(... .. ".info-docks")
require(... .. ".control-center")
require(... .. ".exit_screen")
require(... .. ".lockscreen")
require(... .. ".popups")
